### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by timkodsi** [Medivice/medivice-client-api#1]
Trying to create an issue for practice. I did have difficulty uploading a profile picture on Medivice.com last night.

**Comment by johntayl** [comment]
Hey Tim,

We create issues for the Medivice site under the `Medivice/medivice` repo. [Check it here](https://github.com/Medivice/medivice/issues)

**Comment by timkodsi** [comment]
Hey John,

The link takes me to a 404 page.

Thanks,
Tim

**Comment by johntayl** [comment]
I've created a new team, you should have access to it now.

**Comment by timkodsi** [comment]
Okay, thanks. I think I successfully added an "issue." I won't be adding
much from the tech side of things, but wanted to just check functionality
on Github.

Thanks,
Tim

On Thu, Nov 19, 2015 at 3:27 PM, John Taylor notifications@github.com
wrote:

> I've created a new team, you should have access to it now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Medivice/medivice-client-api/issues/1#issuecomment-158187927
> .

## 

B. Timothy Kodsi, M.D.
